### ISSUE TITLE
[FEATURE] Raise a non-zero exit code on DQ failure when action is set to fail

### ISSUE THREAD

**Issue by holdenk** [Nike-Inc/spark-expectations#42]
**Is your feature request related to a problem? Please describe.**

I use exit codes to determine if I should move to the next step in my pipelines and ideally we would have a non-zero exit code when a dataquality check is set to fail and fails.

**Describe the solution you'd like**
we would have a non-zero exit code when a dataquality check is set to fail and fails.

**Describe alternatives you've considered**

We can use other mechanisms for indicating failure of course, but exit codes are already understood by most pipeline tools.

**Additional context**

See 57 minute mark at https://www.youtube.com/watch?v=bNvvPKv-dmQ

**Comment by asingamaneni** [comment]
@holdenk I was looking at this and found that Spark-Expectations is giving non-zero exit codes when it fails. Upon further investigation found that you have an "echo" command in your code which results always to exit code zero - 

https://github.com/high-performance-spark/high-performance-spark-examples/blob/9d5395cdba58856d6d9c8254b382ffeaaec9b563/run_pyspark_examples.sh#L48

<img width="1397" alt="image" src="https://github.com/Nike-Inc/spark-expectations/assets/25289866/38bfbadc-7732-41c6-aed6-4e87beb2a9d0">

**Comment by holdenk** [comment]
Ooooh! Good catch sorry for the incorrect bug report 😊

**Comment by asingamaneni** [comment]
Thanks, closing the bug report!

**Comment by holdenk** [comment]
Ok so I just redid this without the OR (or well it still has the OR but exits with the same error code unless there is a .fail file) and I checked by executing invalid SQL and it got a non-zero exit, but I did it with a row dq and an agg dq rule and it did not work (see se_complex.json example / minute ~85 in https://www.youtube.com/watch?v=usYELWSZgmE )

**Comment by phanikumarvemuri** [comment]
@holdenk just to make sure that I understand , you are expecting the return code to be non zero because the query_dq should fail and hence the process should exit with non zero ?

But, the query_dq condition `(select count(*) from 3rd_fake_view) < (select input_count from local.dq_stats WHERE table_name='local.3rd_fake' LIMIT 1)` will be evaluated to true because 

`select input_count from local.dq_stats WHERE table_name='local.3rd_fake' LIMIT 1` --- 15267
`select count(*) from 3rd_fake_view` --- 4961. 
and hence the process is exiting with zero

3rd_fake_view: `This view is created after the _row_dq process to run the target agg_dq and query_dq which is input_count-error_count as the action_if_failed is set to drop`


Let me know if my understanding is not correct, or do you have a different perspective on this?

<img width="1499" alt="Screenshot 2023-10-14 at 12 36 59 PM" src="https://github.com/Nike-Inc/spark-expectations/assets/11095154/76707388-0e59-4a58-8d49-85afe4142561">

**Comment by holdenk** [comment]
Ah that's a good point :) For whatever reason I thought the view would have less records but when I flip flop it does fail correctly :)
