### ISSUE TITLE
[BUG] query rule is skipped

### ISSUE THREAD

**Issue by holdenk** [Nike-Inc/spark-expectations#44]
**Describe the bug**

**To Reproduce**

Run the same code as https://github.com/Nike-Inc/spark-expectations/issues/43

**Expected behavior**

Expect rule to run and fail

**Screenshots**

See 1:47 of https://www.youtube.com/watch?v=bNvvPKv-dmQ

**Desktop (please complete the following information):**
1.0

**Additional context**
N/A

**Comment by phanikumarvemuri** [comment]
I will work on it

**Comment by phanikumarvemuri** [comment]
@holdenk When i looked into the rules you used, I see that there is no `row_dq` rule for the table `local.3rd_fake` and `query_dq ` is only enabled only for `target_dq_validation`. For final_query_dq to run there has to be a row_dq rule or `enable_for_source_dq_validation` should be set to true.  The stats also confirms that row_dq is Skipped and final_query_dq is skipped. 

The sequence of execution is
`source_agg_dq`
`source_query_dq`
`row_dq`
`final_agg_dq` only if row_dq is enabled
`final_query_dq` only if row_dq is enabled

<img width="1029" alt="Screenshot 2023-10-11 at 10 03 07 PM" src="https://github.com/Nike-Inc/spark-expectations/assets/11095154/53c4020e-76f0-4aa8-8db9-5d020a8638b1">


https://github.com/Nike-Inc/spark-expectations/blob/ca1ceb5c6a1010b561b211d9b7fa3760f9d08bc6/spark_expectations/core/expectations.py#L436

{"product_id": "pay", "table_name": "local.fake_table_name", "rule_type": "row_dq", "rule": "bonus_checker", "column_name": "MaleBonusPercent", "expectation": "MaleBonusPercent > FemaleBonusPercent", "action_if_failed": "drop", "tag": "", "description": "Sample rule that the male bonuses should be higher. Thankfully this fails (but could be lower base pay etc.)", "enable_for_source_dq_validation": true, "enable_for_target_dq_validation": false, "is_active": true, "enable_error_drop_alert": true, "error_drop_threshold": 1}
{"product_id": "pay", "table_name": "**local.3rd_fake**", "rule_type": "query_dq", "rule": "history", "column_name": "Bloop", "expectation": "(select count(*) from 3rd_fake_view) < (select input_count from local.dq_stats WHERE table_name='local.3rd_fake')", "action_if_failed": "fail", "tag": "", "description": "We should always have more records than before", **"enable_for_source_dq_validation": false**, **"enable_for_target_dq_validation": true**, "is_active": true, "enable_error_drop_alert": true, "error_drop_threshold": 1}

**Comment by holdenk** [comment]
Ah interesting so the aggregate data quality checks are only run if there are row data quality checks present?

**Comment by phanikumarvemuri** [comment]
both agg and query dq rule types can be run on source and target. Here the source input dataframe and target is data filtered/dropped after running rules of type row_dq

**Comment by holdenk** [comment]
I mean you can, although I think that aggregation rules only running if there is a row dq of the same type is something that I did not understand from the docs so I think it would be good to: always run them or update the docs and produce an warning (or error) when encountering a rule which is enabled but will not run.

**Comment by newfront** [comment]
Late to the party here. It feels like a dry-run option could be an interesting pre-integration test to say "no rules table or x for table|stats|x while this will not prevent spark-expectations from running. The benefits of x means y."

I am all for docs where they are applicable but getting warnings or short circuiting in the case of missing definitions would be good for the project too so that a user can do something like:

1. initialize spark-expectations 
2. bootstrap the dq tables - empty if nothing else 
3. run pre-flight. "scanning. zero rules for x (table|view)". Suggestions: (scanned (delta|iceberg|x) table - structure - (table.schema....) - recommended starting rule (x) -> do you want to apply non_null to the columns on table (x)...

I always like being able to fumble and get the package to identify my mistakes. Spark does this nicely with AnalysisExceptions. Delta does similar also with Analysis exceptions. Maybe there is a nice pattern for minimal viable rules with warnings (...)

**Comment by phanikumarvemuri** [comment]
Agree with both the options. 
I will close this issue and will open a feature request to support `dryRun` option  and also to update documentation and add flow chart wherever required
Thanks

**Comment by asingamaneni** [comment]
Dryrun is an awesome thought. Let’s implement it and also update the documentation where necessary!

**Comment by phanikumarvemuri** [comment]
@asingamaneni Can you close this issue. I will open new one for the above features

**Comment by asingamaneni** [comment]
Closing this issue as we will create a new feature request from the above discussion. @phanikumarvemuri please tag this issue when you create a new feature, so that we will know the source for the feature creation.
